services:
  db:
    image: rest-with-asp-net-udemy-db
    command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: dockerfile
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_aspnet_udemy
    ports:
      - 3308:3306
    networks:
      - udemy-network
    
  rest-with-aspnet-udemy:
    image: rest-with-aspnet-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db  
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge